-- Importación de socios desde los reportes HTML de socios 2026-10-03.
-- Se conserva el número de socio original en external_id.
-- Los reportes no contienen email; queda NULL hasta completarlo desde el ABM.

ALTER TABLE members ALTER COLUMN email DROP NOT NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS external_id INTEGER;
ALTER TABLE members ADD COLUMN IF NOT EXISTS address TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS members_external_id_idx ON members(external_id) WHERE external_id IS NOT NULL;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-2', 2, 'Costa Carola', NULL, '', 'SECCION QUINTAS', 'Activo', 'Socio colaborador', 'CC'),
  ('import-3', 3, 'Vicente Ana Maria', NULL, '', 'BORGES 348', 'Activo', 'Socio colaborador', 'VA'),
  ('import-7', 7, 'Diaz Sol', NULL, '', 'JUAN MANUEL DE ROSAS 124', 'Activo', 'Socio colaborador', 'DS'),
  ('import-10', 10, 'Marti Maria Eugenia', NULL, '', '611561', 'Activo', 'Socio colaborador', 'MM'),
  ('import-12', 12, 'Casado Fernanda', NULL, '', 'GRAL PAZ 60', 'Activo', 'Socio colaborador', 'CF'),
  ('import-15', 15, 'Martin Leticia', NULL, '', 'CORTAZA 502', 'Activo', 'Socio colaborador', 'ML'),
  ('import-16', 16, 'Erreca Delfina', NULL, '', 'CORTAZA 502', 'Activo', 'Socio colaborador', 'ED'),
  ('import-21', 21, 'Diaz Veronica', NULL, '', 'PEDRO VIGNAU 282', 'Activo', 'Socio colaborador', 'DV'),
  ('import-23', 23, 'L Hoste Adriana', NULL, '', 'VENEZUELA 345', 'Activo', 'Socio colaborador', 'LH'),
  ('import-24', 24, 'Piñeiro Maria Isabel', NULL, '', 'LUIS MAYOL 231', 'Activo', 'Socio colaborador', 'PM'),
  ('import-27', 27, 'Perez Mariela', NULL, '', 'SAAVEDRA 845', 'Activo', 'Socio colaborador', 'PM'),
  ('import-28', 28, 'Lioca Silvia', NULL, '', 'BOER 546', 'Activo', 'Socio colaborador', 'LS'),
  ('import-30', 30, 'Novillo Veronica', NULL, '', 'GRAL PAZ 654', 'Activo', 'Socio colaborador', 'NV'),
  ('import-32', 32, 'Saganiaz Nora', NULL, '', 'CASTELLI 357', 'Activo', 'Socio colaborador', 'SN'),
  ('import-33', 33, 'Barbieri Angelica', NULL, '', 'AV SAN MARTIN 451', 'Activo', 'Socio colaborador', 'BA'),
  ('import-35', 35, 'Ikes Gilda', NULL, '', 'RONDEAUX 231', 'Activo', 'Socio colaborador', 'IG'),
  ('import-36', 36, 'Masullo Mirta', NULL, '', 'URIBURU 204', 'Activo', 'Socio colaborador', 'MM'),
  ('import-38', 38, 'Fangio Carolina', NULL, '', 'OLASCOAGA 38', 'Activo', 'Socio colaborador', 'FC'),
  ('import-39', 39, 'Suarez Diego', NULL, '', 'DORREGO 364', 'Activo', 'Socio colaborador', 'SD'),
  ('import-43', 43, 'Fernandez Solange', NULL, '', 'IGNACIO RIVAS', 'Activo', 'Socio colaborador', 'FS'),
  ('import-44', 44, 'Fangio Carlos', NULL, '', 'LAPRIDA 278', 'Activo', 'Socio colaborador', 'FC'),
  ('import-46', 46, 'Suarez Marisa Alejandra', NULL, '', 'OLAVARRIA 684', 'Activo', 'Socio colaborador', 'SM'),
  ('import-47', 47, 'Garcia Norberto', NULL, '', 'MORENO 47', 'Activo', 'Socio colaborador', 'GN'),
  ('import-48', 48, 'Santos Raquel', NULL, '', 'MORENO 47', 'Activo', 'Socio colaborador', 'SR'),
  ('import-49', 49, 'Garcia Carolina', NULL, '', 'MORENO 83', 'Activo', 'Socio colaborador', 'GC'),
  ('import-52', 52, 'Miranda Nilda Negrita', NULL, '', 'BELGRANO 336', 'Activo', 'Socio colaborador', 'MN'),
  ('import-54', 54, 'Franco Atilio', NULL, '', 'IGNACIO RIVAS 755', 'Activo', 'Socio colaborador', 'FA'),
  ('import-55', 55, 'Iglesias Alejandra', NULL, '', 'DORREGO 196', 'Activo', 'Socio colaborador', 'IA'),
  ('import-56', 56, 'Sotelo Nelly', NULL, '', 'DORREGO 196', 'Activo', 'Socio colaborador', 'SN'),
  ('import-61', 61, 'Barreiro Giselle', NULL, '', 'COOP ELECTRICA', 'Activo', 'Socio colaborador', 'BG'),
  ('import-62', 62, 'Di Fiore Silvia', NULL, '', 'VENEZUELA 263 DTO', 'Activo', 'Socio colaborador', 'DF'),
  ('import-63', 63, 'Cisneros Norma', NULL, '', 'LAS HERAS 232', 'Activo', 'Socio colaborador', 'CN'),
  ('import-66', 66, 'Ballestero Maria Lujan', NULL, '', 'OLASCOAGA', 'Activo', 'Socio colaborador', 'BM'),
  ('import-67', 67, 'Pontoriero Carina', NULL, '', 'DORREGO 72 GRAL PAZ 524', 'Activo', 'Socio colaborador', 'PC'),
  ('import-68', 68, 'Gonzalez Gimeno Juan Martin', NULL, '', 'CHACO 235', 'Activo', 'Socio colaborador', 'GG'),
  ('import-69', 69, 'Unzue Lujan', NULL, '', '9 DE JULIO 395', 'Activo', 'Socio colaborador', 'UL'),
  ('import-70', 70, 'Castro Eugenia', NULL, '', 'LAVALLE Y PALAVECCINO', 'Activo', 'Socio colaborador', 'CE'),
  ('import-71', 71, 'Toledo Blanca', NULL, '', 'HOGAR DE ANCIANOS', 'Activo', 'Socio colaborador', 'TB'),
  ('import-74', 74, 'Amadori Ana', NULL, '', 'PALAVECCINO 445', 'Activo', 'Socio colaborador', 'AA'),
  ('import-76', 76, 'Hueso Cristina', NULL, '', 'ALMAFUERTE 369', 'Activo', 'Socio colaborador', 'HC'),
  ('import-77', 77, 'Lopez Cristina', NULL, '', 'CHICLANA 463', 'Activo', 'Socio colaborador', 'LC'),
  ('import-78', 78, 'Ricciuto Mercedes', NULL, '2314411646', '', 'Activo', 'Socio colaborador', 'RM'),
  ('import-79', 79, 'Zorrilla Lucrecia', NULL, '2314403161', '', 'Activo', 'Socio colaborador', 'ZL'),
  ('import-85', 85, 'Perez Georgina', NULL, '', 'MITRE 780 VETERINARIA', 'Activo', 'Socio colaborador', 'PG'),
  ('import-86', 86, 'Martinez Federico', NULL, '', 'MITRE780', 'Activo', 'Socio colaborador', 'MF'),
  ('import-87', 87, 'Simon Silvina', NULL, '', 'ALSINA 619 MUNDO GURI', 'Activo', 'Socio colaborador', 'SS'),
  ('import-88', 88, 'Mori Veronica', NULL, '', 'RIVADAVIA 294', 'Activo', 'Socio colaborador', 'MV'),
  ('import-89', 89, 'Delgado Jose Maria', NULL, '', 'LAVALLE 573', 'Activo', 'Socio colaborador', 'DJ'),
  ('import-95', 95, 'Parra Francisco', NULL, '', 'HONDURAS 4004 CABA', 'Activo', 'Socio colaborador', 'PF'),
  ('import-96', 96, 'Campos Susana', NULL, '', 'NECOCHEA 392 FARMACIA COMAS', 'Activo', 'Socio colaborador', 'CS'),
  ('import-97', 97, 'Parra Manuel', NULL, '', 'CORDOBA 3739 CABA', 'Activo', 'Socio colaborador', 'PM'),
  ('import-98', 98, 'Reina Juan Carlos', NULL, '', 'RUTA 226', 'Activo', 'Socio colaborador', 'RJ'),
  ('import-102', 102, 'Ferrari Virginia', NULL, '', 'PELLEGRINI 740', 'Activo', 'Socio colaborador', 'FV'),
  ('import-103', 103, 'Corvalan Adriana', NULL, '', 'IGNACIO RIVAS 646', 'Activo', 'Socio colaborador', 'CA'),
  ('import-104', 104, 'Bolaño Alfredo', NULL, '', 'IGNACIO RIVAS 646', 'Activo', 'Socio colaborador', 'BA'),
  ('import-105', 105, 'Guinea Karina', NULL, '', 'LAPRIDA 545', 'Activo', 'Socio colaborador', 'GK'),
  ('import-106', 106, 'Cisneros Patricia', NULL, '', 'NMATHEU 370', 'Activo', 'Socio colaborador', 'CP'),
  ('import-107', 107, 'Piro Luz Maria', NULL, '', 'ROCA 636', 'Activo', 'Socio colaborador', 'PL'),
  ('import-108', 108, 'Fernandez Javier', NULL, '', 'MATHEU 370', 'Activo', 'Socio colaborador', 'FJ'),
  ('import-109', 109, 'Fernandez Treviño Tomas', NULL, '', '12 Nº183 LAPLATA', 'Activo', 'Socio colaborador', 'FT'),
  ('import-110', 110, 'Mendez Rosana', NULL, '', 'GONET', 'Activo', 'Socio colaborador', 'MR'),
  ('import-111', 111, 'Fernandez Treviño Pablo', NULL, '', 'CORTAZAR 508', 'Activo', 'Socio colaborador', 'FT'),
  ('import-113', 113, 'Giamberluca Araceli', NULL, '', 'ALSINA 131', 'Activo', 'Socio colaborador', 'GA'),
  ('import-114', 114, 'Mendez Marcela', NULL, '', '38 ENTRE 62Y63 LA PLATA', 'Activo', 'Socio colaborador', 'MM'),
  ('import-115', 115, 'Gelabert Yanina', NULL, '', 'BOER 236 LA GERMINADORA', 'Activo', 'Socio colaborador', 'GY'),
  ('import-117', 117, 'Mendez Juan', NULL, '', 'BLAS PAREDA MAR DEL PLATA', 'Activo', 'Socio colaborador', 'MJ'),
  ('import-118', 118, 'Berguez Marina', NULL, '', 'RONDEAUX 136', 'Activo', 'Socio colaborador', 'BM'),
  ('import-119', 119, 'Dadone Maria Lujan', NULL, '', 'AV BROWN 18', 'Activo', 'Socio colaborador', 'DM'),
  ('import-134', 134, 'Olascoaga Laura Carolina', NULL, '', 'ZAPIOLA 745', 'Activo', 'Socio colaborador', 'OL'),
  ('import-137', 137, 'Di Palma Maria Del Carmen', NULL, '', 'BORGES 446', 'Activo', 'Socio colaborador', 'DP'),
  ('import-139', 139, 'Criado Susana', NULL, '', 'LAVALLE 157', 'Activo', 'Socio colaborador', 'CS'),
  ('import-144', 144, 'Cossimo Marco', NULL, '', 'IGNACIO RIVAS 497', 'Activo', 'Socio colaborador', 'CM'),
  ('import-148', 148, 'Castellani Osvaldo', NULL, '', 'LAPRIDA 55', 'Activo', 'Socio colaborador', 'CO'),
  ('import-149', 149, 'Casquero Mariela', NULL, '', 'ALVEAR 455', 'Activo', 'Socio colaborador', 'CM'),
  ('import-152', 152, 'Mancina Natalia', NULL, '', 'ALBERTI 560', 'Activo', 'Socio colaborador', 'MN'),
  ('import-153', 153, 'Duberni Maria Edith', NULL, '', 'ZAPIOLA 23', 'Activo', 'Socio colaborador', 'DM'),
  ('import-155', 155, 'Ives Aguas', NULL, '', 'NECOCHEA36', 'Activo', 'Socio colaborador', 'IA'),
  ('import-156', 156, 'Osovi Retaceria', NULL, '', 'ALSINA 240', 'Activo', 'Socio colaborador', 'OR'),
  ('import-157', 157, 'Beratz Mirta', NULL, '', 'MITRE 470', 'Activo', 'Socio colaborador', 'BM'),
  ('import-158', 158, 'Guinea Micaela', NULL, '', 'R. HERNANDEZ 279', 'Activo', 'Socio colaborador', 'GM'),
  ('import-159', 159, 'Caviglia Maria Del Carmen', NULL, '', 'AZCUENAGA 73', 'Activo', 'Socio colaborador', 'CM'),
  ('import-160', 160, 'Abosalech Maria Milagros', NULL, '', 'ALSINA 131', 'Activo', 'Socio colaborador', 'AM'),
  ('import-163', 163, 'Santos Alba Rosa', NULL, '', 'SANTOS PLAZA 765', 'Activo', 'Socio colaborador', 'SA'),
  ('import-168', 168, 'Aristondo Martin', NULL, '', 'J MARTIN DE ROSAS 1392', 'Activo', 'Socio colaborador', 'AM'),
  ('import-175', 175, 'Remis Ethel', NULL, '', 'PELLEGRINI', 'Activo', 'Socio colaborador', 'RE'),
  ('import-176', 176, 'Morales Carlos Maria', NULL, '', 'GRAL PAZ Y ROCA', 'Activo', 'Socio colaborador', 'MC'),
  ('import-177', 177, 'Moriones Rosana', NULL, '', 'Bº BANCO PROVINCIA CASA15', 'Activo', 'Socio colaborador', 'MR'),
  ('import-178', 178, 'Oyarsabal Emilia', NULL, '', 'BOER 731', 'Activo', 'Socio colaborador', 'OE'),
  ('import-181', 181, 'Terrera Ezequiel', NULL, '', 'RONDEAUX 180', 'Activo', 'Socio colaborador', 'TE'),
  ('import-185', 185, 'Gherbi Jorgelina', NULL, '', 'Bº SOLIDARIDAD CASA64', 'Activo', 'Socio colaborador', 'GJ'),
  ('import-186', 186, 'Mendez Monica', NULL, '', 'CORTAZAR 508', 'Activo', 'Socio colaborador', 'MM'),
  ('import-188', 188, 'Inda Elsa', NULL, '', 'RONDEAUX 24', 'Activo', 'Socio colaborador', 'IE'),
  ('import-192', 192, 'Fosco Carolina', NULL, '', 'MITRE 3238 SALADILLO', 'Activo', 'Socio colaborador', 'FC'),
  ('import-193', 193, 'Santamarina Hector A', NULL, '', 'MITRE 3238 SALADILLO', 'Activo', 'Socio colaborador', 'SH'),
  ('import-194', 194, 'Tourret Eduardo Emilio', NULL, '', 'B DE IRIGOYEN 657', 'Activo', 'Socio colaborador', 'TE'),
  ('import-196', 196, 'Pensa Haydee', NULL, '', 'RONDEAUX 236', 'Activo', 'Socio colaborador', 'PH'),
  ('import-198', 198, 'Vicente Elsa', NULL, '', 'SARGENTO CABRAL 135', 'Activo', 'Socio colaborador', 'VE'),
  ('import-199', 199, 'Mendoza Claudia', NULL, '', 'RAFAEL HERNANDEZ 360', 'Activo', 'Socio colaborador', 'MC'),
  ('import-203', 203, 'Lopez Mariel', NULL, '', 'ROCA 586', 'Activo', 'Socio colaborador', 'LM'),
  ('import-204', 204, 'Yuño Carina', NULL, '', 'Bº JARDIN', 'Activo', 'Socio colaborador', 'YC')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-205', 205, 'Thoman Viviana', NULL, '', 'MORENO 374', 'Activo', 'Socio colaborador', 'TV'),
  ('import-206', 206, 'Lorenzo Silvia', NULL, '', 'REBUCION 28', 'Activo', 'Socio colaborador', 'LS'),
  ('import-207', 207, 'Curcio Adriana', NULL, '', 'LAS HERAS 53', 'Activo', 'Socio colaborador', 'CA'),
  ('import-208', 208, 'Vazquez Carlos', NULL, '', 'SAN MARTIN 1254', 'Activo', 'Socio colaborador', 'VC'),
  ('import-211', 211, 'Green Lidia', NULL, '', 'SARGENTO CABRAL 604', 'Activo', 'Socio colaborador', 'GL'),
  ('import-212', 212, 'Comas Maria Alejandra', NULL, '', 'LAS HERAS 54', 'Activo', 'Socio colaborador', 'CM'),
  ('import-213', 213, 'Falcon Adriana', NULL, '', 'AVELLANEDA 620', 'Activo', 'Socio colaborador', 'FA'),
  ('import-214', 214, 'Pensa Magali', NULL, '', '', 'Activo', 'Socio colaborador', 'PM'),
  ('import-219', 219, 'Del Valio Analia', NULL, '', '9 DE JULIO 545', 'Activo', 'Socio colaborador', 'DV'),
  ('import-221', 221, 'Estrebou Patricia', NULL, '', 'CHICLANA 70', 'Activo', 'Socio colaborador', 'EP'),
  ('import-222', 222, 'Holgado Gabriela', NULL, '', 'SAN MARTIN', 'Activo', 'Socio colaborador', 'HG'),
  ('import-223', 223, 'Montero Monica', NULL, '', 'PROLONG 25 DE MAYO', 'Activo', 'Socio colaborador', 'MM'),
  ('import-224', 224, 'Onorato Graciela', NULL, '', 'RIVADAVIA 1334 CABA', 'Activo', 'Socio colaborador', 'OG'),
  ('import-226', 226, 'Sanchez Alicia', NULL, '', 'SAN MARTIN 1295', 'Activo', 'Socio colaborador', 'SA'),
  ('import-228', 228, 'Iglesias Mariel', NULL, '', 'AVELLANEDA 59', 'Activo', 'Socio colaborador', 'IM'),
  ('import-230', 230, 'Del Petre Nazarena', NULL, '', 'PRINGLES 685 COOPER ELECT', 'Activo', 'Socio colaborador', 'DP'),
  ('import-231', 231, 'Quibus Maria Betina', NULL, '', 'RUTA 226', 'Activo', 'Socio colaborador', 'QM'),
  ('import-235', 235, 'Alonso Laura', NULL, '', '9 DE JULIO 675 COOP ELEC', 'Activo', 'Socio colaborador', 'AL'),
  ('import-236', 236, 'Sabate Maria Alicia', NULL, '', 'AV BROWN 420', 'Activo', 'Socio colaborador', 'SM'),
  ('import-238', 238, 'Abosalech Nahir', NULL, '', 'ALSINA 165', 'Activo', 'Socio colaborador', 'AN'),
  ('import-239', 239, 'Abosalech Amed', NULL, '', 'ALSINA 165', 'Activo', 'Socio colaborador', 'AA'),
  ('import-242', 242, 'Alonso De Bilbao Marisa B.', NULL, '', 'REBUCION 50', 'Activo', 'Socio colaborador', 'AD'),
  ('import-244', 244, 'Comas Gabriela', NULL, '', 'SAN MARTIN 425', 'Activo', 'Socio colaborador', 'CG'),
  ('import-245', 245, 'Alvarez Ana Gabriela', NULL, '', 'DORREGO 158', 'Activo', 'Socio colaborador', 'AA'),
  ('import-246', 246, 'Bopp Mariel Yael', NULL, '', 'PRINGLES 720', 'Activo', 'Socio colaborador', 'BM'),
  ('import-259', 259, 'Unzue Adriana', NULL, '', 'BELGRANO 146', 'Activo', 'Socio colaborador', 'UA'),
  ('import-260', 260, 'Payeras Maria Laura', NULL, '', 'LAS HERAS 245', 'Activo', 'Socio colaborador', 'PM'),
  ('import-262', 262, 'Garcia Choren Ines', NULL, '', 'ALVEAR 85', 'Activo', 'Socio colaborador', 'GC'),
  ('import-266', 266, 'Beguiristain Silvia', NULL, '', 'ALSINA 434', 'Activo', 'Socio colaborador', 'BS'),
  ('import-267', 267, 'Crocce Sergio', NULL, '', 'AV VENEZUELA 650', 'Activo', 'Socio colaborador', 'CS'),
  ('import-268', 268, 'Marquez Andrea', NULL, '', 'AV VENEZUELA 650', 'Activo', 'Socio colaborador', 'MA'),
  ('import-269', 269, 'Curcio Maria Rosa', NULL, '', 'AV GRAL PAZ 350', 'Activo', 'Socio colaborador', 'CM'),
  ('import-270', 270, 'Erreca Jose Grabril', NULL, '', 'MITRE', 'Activo', 'Socio colaborador', 'EJ'),
  ('import-271', 271, 'Cordeu Malena', NULL, '', 'MITRE 650', 'Activo', 'Socio colaborador', 'CM'),
  ('import-272', 272, 'Hueso Alejandro', NULL, '', 'GUEMES 15', 'Activo', 'Socio colaborador', 'HA'),
  ('import-273', 273, 'Artola Juan', NULL, '', 'LAVALLE 130', 'Activo', 'Socio colaborador', 'AJ'),
  ('import-275', 275, 'Lamarque Adrian', NULL, '', 'LAVALLE 124', 'Activo', 'Socio colaborador', 'LA'),
  ('import-278', 278, 'Grismado Graciela', NULL, '', 'NECOCHEA 37', 'Activo', 'Socio colaborador', 'GG'),
  ('import-279', 279, 'Suarez Walter', NULL, '', 'AV SAN MARTIN Y PASSO', 'Activo', 'Socio colaborador', 'SW'),
  ('import-284', 284, 'Calvo Cristina', NULL, '', 'VIAMONTE 117', 'Activo', 'Socio colaborador', 'CC'),
  ('import-288', 288, 'Santos Veronica', NULL, '', 'ROCA 743', 'Activo', 'Socio colaborador', 'SV'),
  ('import-291', 291, 'Paulet Monica Dora', NULL, '', 'AV LAVALLE 371', 'Activo', 'Socio colaborador', 'PM'),
  ('import-292', 292, 'B De Comas Elsa Marialas', NULL, '', 'LAS HERAS 54', 'Activo', 'Socio colaborador', 'BD'),
  ('import-293', 293, 'Sarchione Rosalia', NULL, '', 'LAVALLE 254', 'Activo', 'Socio colaborador', 'SR'),
  ('import-294', 294, 'Farina Maria Gabriela', NULL, '', 'BELGRANO 639', 'Activo', 'Socio colaborador', 'FM'),
  ('import-295', 295, 'Castro Maria Cecilia', NULL, '', 'ALMAFUERTE 532', 'Activo', 'Socio colaborador', 'CM'),
  ('import-296', 296, 'Chatruc Maria Ines', NULL, '', 'RAFAEL HERNANDEZ 279', 'Activo', 'Socio colaborador', 'CM'),
  ('import-297', 297, 'Lescano Claudia', NULL, '', 'MITRE 145', 'Activo', 'Socio colaborador', 'LC'),
  ('import-302', 302, 'Lescano Marcela', NULL, '', 'MITRE 145', 'Activo', 'Socio colaborador', 'LM'),
  ('import-303', 303, 'Mañoso Claudia', NULL, '', 'SARMIENTO 537', 'Activo', 'Socio colaborador', 'MC'),
  ('import-304', 304, 'Sardon Elena', NULL, '', 'URQUIZA 361', 'Activo', 'Socio colaborador', 'SE'),
  ('import-307', 307, 'Torrontegui Cristina', NULL, '', 'ALVARADO 290', 'Activo', 'Socio colaborador', 'TC'),
  ('import-308', 308, 'Hueso Victoria', NULL, '', 'ALVARADO 290', 'Activo', 'Socio colaborador', 'HV'),
  ('import-309', 309, 'Liendo Monica', NULL, '', 'RAFAEL HERNANDEZ 279', 'Activo', 'Socio colaborador', 'LM'),
  ('import-311', 311, 'Iriarte Marita', NULL, '', 'AVELLANEDA 58', 'Activo', 'Socio colaborador', 'IM'),
  ('import-312', 312, 'Mancina Emilia', NULL, '', 'RAFAEL HERNANDEZ 785', 'Activo', 'Socio colaborador', 'ME'),
  ('import-313', 313, 'Sanchez Cristian', NULL, '', 'CENTENARIO 455 BCO PCIA', 'Activo', 'Socio colaborador', 'SC'),
  ('import-315', 315, 'Hoffman Yesica', NULL, '', 'BERNARDO DE IRIGOYEN 575', 'Activo', 'Socio colaborador', 'HY'),
  ('import-319', 319, 'Gomez Pamela', NULL, '', 'ARENALES 740', 'Activo', 'Socio colaborador', 'GP'),
  ('import-320', 320, 'Romera Gisela', NULL, '', 'MATHEU 15', 'Activo', 'Socio colaborador', 'RG'),
  ('import-323', 323, 'Galan Micaela', NULL, '', 'RIVADAVIA 499', 'Activo', 'Socio colaborador', 'GM'),
  ('import-324', 324, 'Laborde Johana', NULL, '', 'OLAVARRIA 297', 'Activo', 'Socio colaborador', 'LJ'),
  ('import-326', 326, 'Echeverry Gaston', NULL, '', 'PELLEGRINI 434', 'Activo', 'Socio colaborador', 'EG'),
  ('import-327', 327, 'Antoniano Adriana', NULL, '', 'SANTA FE 2130 CABA', 'Activo', 'Socio colaborador', 'AA'),
  ('import-328', 328, 'Videla Louteau Antonia', NULL, '', 'OLLEROS 2739 CABA', 'Activo', 'Socio colaborador', 'VL'),
  ('import-329', 329, 'Artola Jose Ramon Miki', NULL, '', 'FORMOSA 41', 'Activo', 'Socio colaborador', 'AJ'),
  ('import-330', 330, 'Oriozabala Lorena', NULL, '', 'FORMOSA 41', 'Activo', 'Socio colaborador', 'OL'),
  ('import-333', 333, 'Bucheler Graciela', NULL, '', 'ALVARADO 465', 'Activo', 'Socio colaborador', 'BG'),
  ('import-334', 334, 'Alvarez Norma', NULL, '', 'BOER 350', 'Activo', 'Socio colaborador', 'AN'),
  ('import-335', 335, 'Hernandez Edita', NULL, '', 'OLAVARRIA 727', 'Activo', 'Socio colaborador', 'HE'),
  ('import-338', 338, 'Piermatei Claudia', NULL, '', 'LAPRIDA 124', 'Activo', 'Socio colaborador', 'PC'),
  ('import-339', 339, 'Otano Karina', NULL, '', 'PRINGLES 345', 'Activo', 'Socio colaborador', 'OK'),
  ('import-340', 340, 'Artola Maria Alicia', NULL, '', 'PRINGLES 236', 'Activo', 'Socio colaborador', 'AM'),
  ('import-343', 343, 'Frau Andrea', NULL, '', 'BELGRANO 785', 'Activo', 'Socio colaborador', 'FA'),
  ('import-344', 344, 'Arcomano Graciela', NULL, '', 'RONDEAUX 229', 'Activo', 'Socio colaborador', 'AG'),
  ('import-345', 345, 'Maluendez Jose Maria', NULL, '', 'SIMON BOLIVAR 163', 'Activo', 'Socio colaborador', 'MJ'),
  ('import-346', 346, 'Sardon Marcelo', NULL, '', 'BºLATINO 205', 'Activo', 'Socio colaborador', 'SM'),
  ('import-348', 348, 'Garcia Matias', NULL, '', 'MORENO 47', 'Activo', 'Socio colaborador', 'GM'),
  ('import-349', 349, 'Garcia Ariel', NULL, '', 'MORENO 47', 'Activo', 'Socio colaborador', 'GA'),
  ('import-350', 350, 'Arioni Olga Mabel', NULL, '', 'SAAVEDRA 200', 'Activo', 'Socio colaborador', 'AO'),
  ('import-351', 351, 'Bacas Olga Susana', NULL, '', 'AV SAN MARTIN 980', 'Activo', 'Socio colaborador', 'BO'),
  ('import-352', 352, 'Gonzalez Pablo Kineciologo', NULL, '', 'LAPRIDA', 'Activo', 'Socio colaborador', 'GP'),
  ('import-353', 353, 'Erreca Florencia', NULL, '', 'OLAVARRIA 566', 'Activo', 'Socio colaborador', 'EF'),
  ('import-356', 356, 'Mosca Matias', NULL, '', 'AV SAN MARTIN 380', 'Activo', 'Socio colaborador', 'MM'),
  ('import-357', 357, 'Baracat Yamil', NULL, '', 'SARMIENTO 599', 'Activo', 'Socio colaborador', 'BY'),
  ('import-358', 358, 'Rossi Roberto', NULL, '', 'OLAVARRIA 195', 'Activo', 'Socio colaborador', 'RR'),
  ('import-360', 360, 'Aguirre Carolina', NULL, '', 'NECOCHEA 305', 'Activo', 'Socio colaborador', 'AC'),
  ('import-361', 361, 'Zabaljauregui Julio', NULL, '', 'NECOCHEA 305', 'Activo', 'Socio colaborador', 'ZJ'),
  ('import-362', 362, 'Chillon Fabian', NULL, '', 'ALVARADO 540', 'Activo', 'Socio colaborador', 'CF'),
  ('import-364', 364, 'Manso Ieda', NULL, '', 'VIAMONTE 510', 'Activo', 'Socio colaborador', 'MI'),
  ('import-367', 367, 'Navarro Natalia', NULL, '', 'ROCA 49', 'Activo', 'Socio colaborador', 'NN'),
  ('import-369', 369, 'Palomino Emilia', NULL, '', 'PROL RIVADAVIA', 'Activo', 'Socio colaborador', 'PE'),
  ('import-372', 372, 'Martin Graciela', NULL, '', 'QUIRNO ACOSTA 477', 'Activo', 'Socio colaborador', 'MG'),
  ('import-373', 373, 'Diez Adriana', NULL, '', 'URQUIZA 568', 'Activo', 'Socio colaborador', 'DA'),
  ('import-374', 374, 'Gimeno Graciela', NULL, '', 'CHACO 235', 'Activo', 'Socio colaborador', 'GG'),
  ('import-376', 376, 'Carona Lorena', NULL, '', 'MATHEU 512', 'Activo', 'Socio colaborador', 'CL'),
  ('import-377', 377, 'Cabrera Carolina', NULL, '', 'PRINGLES 455', 'Activo', 'Socio colaborador', 'CC'),
  ('import-378', 378, 'Bruno Claudia', NULL, '', 'PELLEGRINI 773', 'Activo', 'Socio colaborador', 'BC'),
  ('import-383', 383, 'Feoli Veronica', NULL, '', 'REBUCION 366', 'Activo', 'Socio colaborador', 'FV'),
  ('import-386', 386, 'Caivano Graciela', NULL, '', 'CORTAZAR 464', 'Activo', 'Socio colaborador', 'CG')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-389', 389, 'Di Bernardi Adriana', NULL, '', '', 'Activo', 'Socio colaborador', 'DB'),
  ('import-390', 390, 'Santilli Graciela', NULL, '', 'MITRE 431', 'Activo', 'Socio colaborador', 'SG'),
  ('import-395', 395, 'Airala Carolina', NULL, '', 'SAENZ PEÑA 1450', 'Activo', 'Socio colaborador', 'AC'),
  ('import-397', 397, 'Villalba Alejandra', NULL, '', 'RONDEAUX 444', 'Activo', 'Socio colaborador', 'VA'),
  ('import-398', 398, 'Ladux Sergio', NULL, '', 'BORGES 597', 'Activo', 'Socio colaborador', 'LS'),
  ('import-401', 401, 'Delorenzi Maria Elina', NULL, '', 'PALAVECCINO 435 DIARIO LA MAÑANA', 'Activo', 'Socio colaborador', 'DM'),
  ('import-403', 403, 'Molfese Maria Marta', NULL, '', 'RODRIGUEZ PEÑA 217', 'Activo', 'Socio colaborador', 'MM'),
  ('import-406', 406, 'Guinea Valeria', NULL, '', 'VIAMONTE 61', 'Activo', 'Socio colaborador', 'GV'),
  ('import-407', 407, 'Suarez Romina', NULL, '', 'ALMAFUERTE 734', 'Activo', 'Socio colaborador', 'SR'),
  ('import-408', 408, 'Cuello Julieta', NULL, '', 'CACIQUE PINCE', 'Activo', 'Socio colaborador', 'CJ'),
  ('import-409', 409, 'Palomeque Sergio', NULL, '', 'OLAVARRIA 435', 'Activo', 'Socio colaborador', 'PS'),
  ('import-411', 411, 'Los Arco Analia', NULL, '', 'RIVADAVIA 340', 'Activo', 'Socio colaborador', 'LA'),
  ('import-412', 412, 'Esteban Mariana', NULL, '', 'ALVEAR 260', 'Activo', 'Socio colaborador', 'EM'),
  ('import-419', 419, 'Gallo De Herrera Patricia', NULL, '', 'Chiclana 75', 'Activo', 'Socio colaborador', 'GD'),
  ('import-420', 420, 'Romera Marta', NULL, '', '', 'Activo', 'Socio colaborador', 'RM'),
  ('import-421', 421, 'Groba -Benito Elba', NULL, '', 'SAN MARTIN', 'Activo', 'Socio colaborador', 'G-'),
  ('import-423', 423, 'Legorburu Maria Ines', NULL, '', 'SAN MARTIN Y LAPRIDA', 'Activo', 'Socio colaborador', 'LM'),
  ('import-426', 426, 'Moreno Daniel', NULL, '', 'DORREGO', 'Activo', 'Socio colaborador', 'MD'),
  ('import-429', 429, 'Capiello Liliana', NULL, '', 'PASO 354', 'Activo', 'Socio colaborador', 'CL'),
  ('import-430', 430, 'Coria Veronica', NULL, '', 'SAN MARTIN 256', 'Activo', 'Socio colaborador', 'CV'),
  ('import-432', 432, 'Llarenas Alejandro', NULL, '', 'RODRIGUEZ PEÑA 153', 'Activo', 'Socio colaborador', 'LA'),
  ('import-433', 433, 'Giles Patricia', NULL, '', 'ALVEAR 325', 'Activo', 'Socio colaborador', 'GP'),
  ('import-442', 442, 'Danessa Virginia', NULL, '', 'MATHEU 175', 'Activo', 'Socio colaborador', 'DV'),
  ('import-445', 445, 'Ottonelli Daniela', NULL, '', 'SAN JUAN 568', 'Activo', 'Socio colaborador', 'OD'),
  ('import-447', 447, 'Badano Veronica', NULL, '', 'ALVARADO 880', 'Activo', 'Socio colaborador', 'BV'),
  ('import-451', 451, 'Perez Viviana Monica', NULL, '', 'LAVALLE 255', 'Activo', 'Socio colaborador', 'PV'),
  ('import-452', 452, 'Martin Daniela', NULL, '', 'QUIRNO ACOSTA Y NECOCHEA', 'Activo', 'Socio colaborador', 'MD'),
  ('import-453', 453, 'Lacalle Agustina', NULL, '', 'Bº COOP CASA 2 TARJETA NARANJA', 'Activo', 'Socio colaborador', 'LA'),
  ('import-454', 454, 'Videla Louteau Alfonso', NULL, '', 'OLLEROS 2739 CABA', 'Activo', 'Socio colaborador', 'VL'),
  ('import-456', 456, 'Lopardo Luisa Liliana', NULL, '', '', 'Activo', 'Socio colaborador', 'LL'),
  ('import-458', 458, 'Apesteguia Silvia', NULL, '', 'ALBERTI 1365 CASA 59', 'Activo', 'Socio colaborador', 'AS'),
  ('import-460', 460, 'Gonzalez Prieto Juan Manuel', NULL, '', 'Bº LOS TILOS TUCUMAN 146', 'Activo', 'Socio colaborador', 'GP'),
  ('import-470', 470, 'Albor Rocio Soledad', NULL, '', 'SANTIAGO DEL ESTERO', 'Activo', 'Socio colaborador', 'AR'),
  ('import-471', 471, 'Hernandez Liliana', NULL, '', 'VENEZUELA 279', 'Activo', 'Socio colaborador', 'HL'),
  ('import-474', 474, 'Berreterrex Sonia', NULL, '', 'RIVADAVIA 66', 'Activo', 'Socio colaborador', 'BS'),
  ('import-475', 475, 'Alvarez Nancy', NULL, '', 'NICOLAS OCAMPO Y CHACO', 'Activo', 'Socio colaborador', 'AN'),
  ('import-477', 477, 'Canepare Maria', NULL, '', 'LAS HERAS 120', 'Activo', 'Socio colaborador', 'CM'),
  ('import-478', 478, 'Otano Maria Jose', NULL, '', 'cuenta DNI', 'Activo', 'Socio colaborador', 'OM'),
  ('import-481', 481, 'Reina Maria Fernanda', NULL, '', 'AV BELGRANO 980', 'Activo', 'Socio colaborador', 'RM'),
  ('import-482', 482, 'Reina Maria Eugenia', NULL, '', 'AV 9 DE JULIO', 'Activo', 'Socio colaborador', 'RM'),
  ('import-483', 483, 'Quibus Maria Cristina', NULL, '', 'SARMIENTO 639', 'Activo', 'Socio colaborador', 'QM'),
  ('import-484', 484, 'March Alicia', NULL, '', 'RUTA 226 SECC5', 'Activo', 'Socio colaborador', 'MA'),
  ('import-487', 487, 'Fernandez Guillermo', NULL, '', 'OLASCOAGA 33', 'Activo', 'Socio colaborador', 'FG'),
  ('import-490', 490, 'Garat Eugenia', NULL, '', 'AV BROWN 50', 'Activo', 'Socio colaborador', 'GE'),
  ('import-491', 491, 'Angeli Daniela', NULL, '', 'VENEZUELA 189', 'Activo', 'Socio colaborador', 'AD'),
  ('import-494', 494, 'San Juan Susana', NULL, '', 'DORREGO 481', 'Activo', 'Socio colaborador', 'SJ'),
  ('import-495', 495, 'Sarchioni Sergio', NULL, '', 'ALVEAR 150 ANSES', 'Activo', 'Socio colaborador', 'SS'),
  ('import-502', 502, 'Tordo Cesar', NULL, '', 'ACC SOCIAL', 'Activo', 'Socio colaborador', 'TC'),
  ('import-504', 504, 'Di Bernardi Juan', NULL, '', 'PALAVECCINO 445', 'Activo', 'Socio colaborador', 'DB'),
  ('import-505', 505, 'Perez Olga', NULL, '', 'EDISON 336', 'Activo', 'Socio colaborador', 'PO'),
  ('import-506', 506, 'Ainesa Lara', NULL, '', 'SECCION QUINTA', 'Activo', 'Socio colaborador', 'AL'),
  ('import-507', 507, 'Robles Mariela', NULL, '', 'RIVADAVIA 674', 'Activo', 'Socio colaborador', 'RM'),
  ('import-508', 508, 'Gorosito Maria Emilia', NULL, '', 'REBUCION 132', 'Activo', 'Socio colaborador', 'GM'),
  ('import-510', 510, 'Mangini Soledad', NULL, '', '', 'Activo', 'Socio colaborador', 'MS'),
  ('import-513', 513, 'Criado Ricardo', NULL, '', 'SARMIENTO 450', 'Activo', 'Socio colaborador', 'CR'),
  ('import-514', 514, 'Bella Donna', NULL, '', 'OLAVARRIA 177', 'Activo', 'Socio colaborador', 'BD'),
  ('import-515', 515, 'Moriones Erica', NULL, '', 'COLON 437', 'Activo', 'Socio colaborador', 'ME'),
  ('import-517', 517, 'Paoletti Carlos Horacio', NULL, '', 'SARMIENTO Y ZAPIOLA', 'Activo', 'Socio colaborador', 'PC'),
  ('import-518', 518, 'Tambureli Silvia', NULL, '', 'PELLEGRINI 684', 'Activo', 'Socio colaborador', 'TS'),
  ('import-519', 519, 'Moran Nicolas', NULL, '', 'BANCO SANTANDER', 'Activo', 'Socio colaborador', 'MN'),
  ('import-520', 520, 'Barrio Mariela', NULL, '', 'BCO SANTANDER NICOLAS MORAN', 'Activo', 'Socio colaborador', 'BM'),
  ('import-523', 523, 'Danessa Carolina', NULL, '', 'BANCO SANTANDER', 'Activo', 'Socio colaborador', 'DC'),
  ('import-524', 524, 'Colato Maria Pia', NULL, '', 'BANCO SANTANDER', 'Activo', 'Socio colaborador', 'CM'),
  ('import-526', 526, 'Di Domenico Laura', NULL, '', 'MITRE 232', 'Activo', 'Socio colaborador', 'DD'),
  ('import-528', 528, 'Niell Monica', NULL, '', 'VENEZUELA 545', 'Activo', 'Socio colaborador', 'NM'),
  ('import-529', 529, 'Sabatoni Silvina', NULL, '', '624997', 'Activo', 'Socio colaborador', 'SS'),
  ('import-530', 530, 'Orfanelli Gabriela', NULL, '', 'ALBERTI 1271', 'Activo', 'Socio colaborador', 'OG'),
  ('import-531', 531, 'Oroz Patricia', NULL, '', 'PICHICARUHE 635', 'Activo', 'Socio colaborador', 'OP'),
  ('import-532', 532, 'Duhart Laura', NULL, '', 'PASO 14', 'Activo', 'Socio colaborador', 'DL'),
  ('import-538', 538, 'Luengo Nahuel', NULL, '', 'Q ACOSTA 356', 'Activo', 'Socio colaborador', 'LN'),
  ('import-541', 541, 'Cardacce Agustin', NULL, '', 'LAPRIDA 564', 'Activo', 'Socio colaborador', 'CA'),
  ('import-542', 542, 'Aguilar Lucrecia', NULL, '', 'B JARDIN ALRA', 'Activo', 'Socio colaborador', 'AL'),
  ('import-543', 543, 'Achuelo Javier', NULL, '', 'DORREGO 634 ALRA', 'Activo', 'Socio colaborador', 'AJ'),
  ('import-545', 545, 'Carrizo Lujan', NULL, '', 'R PEÑA 145 ALRA', 'Activo', 'Socio colaborador', 'CL'),
  ('import-547', 547, 'Garcia Marianela', NULL, '', 'LUIS MAYOL 536 ALRA', 'Activo', 'Socio colaborador', 'GM'),
  ('import-549', 549, 'Rodriguez Aldo', NULL, '', 'OLASCOAGA 215', 'Activo', 'Socio colaborador', 'RA'),
  ('import-551', 551, 'Cifuni Hernan', NULL, '', 'RUTA226 KM 398.5 ALRA', 'Activo', 'Socio colaborador', 'CH'),
  ('import-552', 552, 'Acosta Maria Julia', NULL, '', 'RUTA226 KM 398.5 ALRA', 'Activo', 'Socio colaborador', 'AM'),
  ('import-555', 555, 'Lotto Alicia', NULL, '', 'B COOP 121 ALRA', 'Activo', 'Socio colaborador', 'LA'),
  ('import-556', 556, 'Gomez Clara Soledad', NULL, '', 'I RIVAS 765', 'Activo', 'Socio colaborador', 'GC'),
  ('import-558', 558, 'Campero Y Montenegro Rosa', NULL, '', '', 'Activo', 'Socio colaborador', 'CY'),
  ('import-560', 560, 'Martinez Rodolfo', NULL, '', 'LAPRIDA 537', 'Activo', 'Socio colaborador', 'MR'),
  ('import-565', 565, 'Lopez Patricia', NULL, '', 'BCO PCIA', 'Activo', 'Socio colaborador', 'LP'),
  ('import-566', 566, 'Manfredo Florencia', NULL, '', 'QUIRNO COSTA 195', 'Activo', 'Socio colaborador', 'MF'),
  ('import-567', 567, 'Alonso Gabriela', NULL, '', 'PRINGLES 620', 'Activo', 'Socio colaborador', 'AG'),
  ('import-568', 568, 'Westdorp Sonia', NULL, '', 'NECOCHEA 351', 'Activo', 'Socio colaborador', 'WS'),
  ('import-569', 569, 'Martin Yanina', NULL, '', 'B VILLA DIAMANTE', 'Activo', 'Socio colaborador', 'MY'),
  ('import-570', 570, 'Martin Cristian', NULL, '', 'QUIRNO ACOSTA 195', 'Activo', 'Socio colaborador', 'MC'),
  ('import-571', 571, 'Martin Diego', NULL, '', 'OLAVARRIA 520', 'Activo', 'Socio colaborador', 'MD'),
  ('import-572', 572, 'Martin Abril', NULL, '', 'QUIRNO ACOSTA 195', 'Activo', 'Socio colaborador', 'MA'),
  ('import-573', 573, 'Arne Lilia', NULL, '', 'ALVARADO 120', 'Activo', 'Socio colaborador', 'AL'),
  ('import-576', 576, 'Martinez Stela Maris', NULL, '', 'ARENALES 747', 'Activo', 'Socio colaborador', 'MS'),
  ('import-578', 578, 'Mansilla Carolina', NULL, '', 'VENEZUELA 727', 'Activo', 'Socio colaborador', 'MC'),
  ('import-579', 579, 'Viera Silvia', NULL, '', 'CARLOS GARDEL 125', 'Activo', 'Socio colaborador', 'VS'),
  ('import-581', 581, 'Roman Mirian', NULL, '', 'PALAVECCINO Y MORENO', 'Activo', 'Socio colaborador', 'RM'),
  ('import-582', 582, 'Pensa Graciela', NULL, '', 'R Hernandez escribania DAndre', 'Activo', 'Socio colaborador', 'PG'),
  ('import-583', 583, 'D Andrea Jose Luis', NULL, '', 'R. Hernandez Escribania', 'Activo', 'Socio colaborador', 'DA'),
  ('import-586', 586, 'Manzano Maria Laura', NULL, '', '', 'Activo', 'Socio colaborador', 'MM'),
  ('import-587', 587, 'Luque Marcela', NULL, '', 'BARTON 735 V DIAMANTE', 'Activo', 'Socio colaborador', 'LM'),
  ('import-588', 588, 'Luengo Mariela', NULL, '', 'NECOCHEA 346 CONSEJO ESCOLAR', 'Activo', 'Socio colaborador', 'LM')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-589', 589, 'Arena Maria Virginia', NULL, '', 'OLAVARRIA 387', 'Activo', 'Socio colaborador', 'AM'),
  ('import-590', 590, 'Asin Yamile', NULL, '', 'LIBRERÍA ABC', 'Activo', 'Socio colaborador', 'AY'),
  ('import-591', 591, 'Arabehere Emma', NULL, '', 'LIBRERÍA ABC', 'Activo', 'Socio colaborador', 'AE'),
  ('import-592', 592, 'Piro Mabel', NULL, '', '', 'Activo', 'Socio colaborador', 'PM'),
  ('import-593', 593, 'Suarez Nestor', NULL, '', '', 'Activo', 'Socio colaborador', 'SN'),
  ('import-594', 594, 'Flores Pablo', NULL, '', 'TEHUELCHES S/N', 'Activo', 'Socio colaborador', 'FP'),
  ('import-595', 595, 'Frassa Maria Agustina', NULL, '', 'TEHUELCHES S/N', 'Activo', 'Socio colaborador', 'FM'),
  ('import-598', 598, 'Uahb Carola', NULL, '', 'TUCUMAN 175', 'Activo', 'Socio colaborador', 'UC'),
  ('import-599', 599, 'Colombo Marcelo', NULL, '', 'NECOCHEA 679', 'Activo', 'Socio colaborador', 'CM'),
  ('import-600', 600, 'Viola Daniela', NULL, '', 'PRINGLES 87', 'Activo', 'Socio colaborador', 'VD'),
  ('import-602', 602, 'Crocce Jorgelina', NULL, '', 'ALBERTI 559', 'Activo', 'Socio colaborador', 'CJ'),
  ('import-603', 603, 'Sigal Susana', NULL, '', 'ZAPIOLA 56', 'Activo', 'Socio colaborador', 'SS'),
  ('import-609', 609, 'Carroze Lucrecia', NULL, '', 'B COOP CASA 15', 'Activo', 'Socio colaborador', 'CL'),
  ('import-611', 611, 'Acosta Maria Elisabet', NULL, '', 'DIAG ROTTETA 48 PIROVANO', 'Activo', 'Socio colaborador', 'AM'),
  ('import-613', 613, 'Echave Ada Norma', NULL, '', 'LAUREANO RODRIGUEZ 76 PIROV', 'Activo', 'Socio colaborador', 'EA'),
  ('import-616', 616, 'Fortunato Valeria', NULL, '', 'RIVADAVIA 860', 'Activo', 'Socio colaborador', 'FV'),
  ('import-617', 617, 'Santiago Micaela', NULL, '', 'LAPRIDA 350', 'Activo', 'Socio colaborador', 'SM'),
  ('import-618', 618, 'Laurence Maria Ines', NULL, '', 'ITALIA 278', 'Activo', 'Socio colaborador', 'LM'),
  ('import-619', 619, 'Tadeo Silvia Nora', NULL, '', '', 'Activo', 'Socio colaborador', 'TS'),
  ('import-620', 620, 'Diaz Eugenia', NULL, '', 'AVELLANEDA 101', 'Activo', 'Socio colaborador', 'DE'),
  ('import-621', 621, 'Gonzalez Veronica', NULL, '', '', 'Activo', 'Socio colaborador', 'GV'),
  ('import-622', 622, 'Mangas Andrea', NULL, '', 'CHICLANA 575', 'Activo', 'Socio colaborador', 'MA'),
  ('import-623', 623, 'Nievas Silvina', NULL, '', 'MATHEU 583', 'Activo', 'Socio colaborador', 'NS'),
  ('import-624', 624, 'Gomez Maria Angeles', NULL, '', '', 'Activo', 'Socio colaborador', 'GM'),
  ('import-627', 627, 'Lapenna Gustavo', NULL, '', 'HIERROS BOLIVAR', 'Activo', 'Socio colaborador', 'LG'),
  ('import-628', 628, 'Bianco M. Paula', NULL, '', 'consultorio casona de Pascuet', 'Activo', 'Socio colaborador', 'BM'),
  ('import-630', 630, 'Mendoza Romina', NULL, '', '475756', 'Activo', 'Socio colaborador', 'MR'),
  ('import-632', 632, 'Calieni Juan Cruz', NULL, '', 'Casona de Pascuet', 'Activo', 'Socio colaborador', 'CJ'),
  ('import-633', 633, 'Berdesegar Sebastian', NULL, '', 'N. OCAMPO 20', 'Activo', 'Socio colaborador', 'BS'),
  ('import-634', 634, 'Fernandez Treviño Ivana', NULL, '', 'MORENO 1157 OLAVARRIA', 'Activo', 'Socio colaborador', 'FT'),
  ('import-636', 636, 'Santa Maria Maria Gabriela', NULL, '', 'MUNDO GURI', 'Activo', 'Socio colaborador', 'SM'),
  ('import-637', 637, 'Schwab Claudia', NULL, '', 'FALUCHO 640', 'Activo', 'Socio colaborador', 'SC'),
  ('import-638', 638, 'Albor Marisol', NULL, '', 'B PARERA 1133 MDQ', 'Activo', 'Socio colaborador', 'AM'),
  ('import-639', 639, 'Raczko Margarita', NULL, '', 'B PARERA 1133 MDQ', 'Activo', 'Socio colaborador', 'RM'),
  ('import-640', 640, 'Santamarina Josefina', NULL, '', 'MITRE 3238 SALADILLO', 'Activo', 'Socio colaborador', 'SJ'),
  ('import-642', 642, 'Robalosantos Daniela', NULL, '', 'EMPLEADA DE CASTELANI', 'Activo', 'Socio colaborador', 'RD'),
  ('import-643', 643, 'Ramponi Daniela', NULL, '', 'CAPEDRONI 30', 'Activo', 'Socio colaborador', 'RD'),
  ('import-644', 644, 'Sardon Antonella', NULL, '', '614928', 'Activo', 'Socio colaborador', 'SA'),
  ('import-650', 650, 'Schmoll Georgina', NULL, '', 'RIVADAVIA 577 URDAMPILLETA', 'Activo', 'Socio colaborador', 'SG'),
  ('import-653', 653, 'Gonzalez Mirta', NULL, '', '460588', 'Activo', 'Socio colaborador', 'GM'),
  ('import-654', 654, 'Caldara Marcela', NULL, '', '552749', 'Activo', 'Socio colaborador', 'CM'),
  ('import-655', 655, 'Herrero Valeria', NULL, '', '511620', 'Activo', 'Socio colaborador', 'HV'),
  ('import-656', 656, 'Hernandez Stella', NULL, '', '519026', 'Activo', 'Socio colaborador', 'HS'),
  ('import-657', 657, 'Calvo M. Jose', NULL, '', '446356', 'Activo', 'Socio colaborador', 'CM'),
  ('import-658', 658, 'Font Alejandra', NULL, '', '445697', 'Activo', 'Socio colaborador', 'FA'),
  ('import-659', 659, 'Font M. Celeste', NULL, '', '519710', 'Activo', 'Socio colaborador', 'FM'),
  ('import-660', 660, 'Gonzalez Cristina', NULL, '', '407772', 'Activo', 'Socio colaborador', 'GC'),
  ('import-661', 661, 'Cernadas Elena', NULL, '', '543253', 'Activo', 'Socio colaborador', 'CE'),
  ('import-662', 662, 'Font Osvaldo', NULL, '', '539101', 'Activo', 'Socio colaborador', 'FO'),
  ('import-663', 663, 'Gourdon Nora', NULL, '', '611010', 'Activo', 'Socio colaborador', 'GN'),
  ('import-664', 664, 'Martinez M. Alejandra', NULL, '', '401331', 'Activo', 'Socio colaborador', 'MM'),
  ('import-668', 668, 'Sanchez M. Eugenia', NULL, '', 'brown 465', 'Activo', 'Socio colaborador', 'SM'),
  ('import-669', 669, 'Oyarguren Martin', NULL, '', 'GONNET', 'Activo', 'Socio colaborador', 'OM'),
  ('import-670', 670, 'Oyarguren Martina', NULL, '', 'GONNET', 'Activo', 'Socio colaborador', 'OM'),
  ('import-671', 671, 'Oyarguren Catalina', NULL, '', 'GONNET', 'Activo', 'Socio colaborador', 'OC'),
  ('import-673', 673, 'Zabatoni Claudia', NULL, '', 'VIAMONTE 49', 'Activo', 'Socio colaborador', 'ZC'),
  ('import-674', 674, 'Robredo Noelia', NULL, '', 'BALCARCE 730', 'Activo', 'Socio colaborador', 'RN'),
  ('import-675', 675, 'Sardon Marcela', NULL, '', 'CASA205 B.LATINO', 'Activo', 'Socio colaborador', 'SM'),
  ('import-676', 676, 'Sarnari Benerise Fernanda', NULL, '', '512235', 'Activo', 'Socio colaborador', 'SB'),
  ('import-678', 678, 'Pacho Romina', NULL, '', '443226', 'Activo', 'Socio colaborador', 'PR'),
  ('import-679', 679, 'Jhon Andrea', NULL, '', 'saavedra 595 urdampilleta', 'Activo', 'Socio colaborador', 'JA'),
  ('import-680', 680, 'Taddeo Marcela', NULL, '', 'SAn martin 732', 'Activo', 'Socio colaborador', 'TM'),
  ('import-683', 683, 'Palacios M, Laura', NULL, '', 'DEL MONTE 625 CALFUCURA', 'Activo', 'Socio colaborador', 'PM'),
  ('import-684', 684, 'Guisolfo Lorena', NULL, '', '9 DE JULIO 357', 'Activo', 'Socio colaborador', 'GL'),
  ('import-686', 686, 'Alonso ,mariel', NULL, '', '571698', 'Activo', 'Socio colaborador', 'A,'),
  ('import-687', 687, 'Alli Maria Alejandra', NULL, '', 'BELGRANO 366', 'Activo', 'Socio colaborador', 'AM'),
  ('import-688', 688, 'Carona Veronica', NULL, '', 'PELLEGRINI 871 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CV'),
  ('import-689', 689, 'Berre Maria Daniela', NULL, '', 'PUEYRREDON 338 URDAMPILLETA', 'Activo', 'Socio colaborador', 'BM'),
  ('import-690', 690, 'Bono Luciano', NULL, '', 'F.LOPEZ 885 URDAMPILLETA', 'Activo', 'Socio colaborador', 'BL'),
  ('import-691', 691, 'Merodio Melisa', NULL, '', 'F. LOPEZ 885 URDAMPILLETA', 'Activo', 'Socio colaborador', 'MM'),
  ('import-692', 692, 'Ricci Nelda Luisa', NULL, '', 'H.IRI GOYEN 47 URDAMPILLETA', 'Activo', 'Socio colaborador', 'RN'),
  ('import-693', 693, 'Laurence Norma Beatriz', NULL, '', 'PASTEUR 264 URDAMPILLETA', 'Activo', 'Socio colaborador', 'LN'),
  ('import-694', 694, 'Alos Alejandra Mercedes', NULL, '', 'ESPAÑA 322 URDAMPILLETA', 'Activo', 'Socio colaborador', 'AA'),
  ('import-695', 695, 'Volpi Beatriz', NULL, '', 'SAAVEDRA 241 URDAMPILLETA', 'Activo', 'Socio colaborador', 'VB'),
  ('import-696', 696, 'Essaipe Marta Estela', NULL, '', 'PUEYRREDON 651 URDAMPILLETA', 'Activo', 'Socio colaborador', 'EM'),
  ('import-697', 697, 'Mendez Diego', NULL, '', 'MONTES DE OCA 255 CASTELAR', 'Activo', 'Socio colaborador', 'MD'),
  ('import-698', 698, 'Serricho Bula Adriana', NULL, '', 'J DEL CAMPILLO 2837 CABA', 'Activo', 'Socio colaborador', 'SB'),
  ('import-699', 699, 'Vicente Liliana', NULL, '', 'H. IRIGOYEN 128 URDAMPILLETA', 'Activo', 'Socio colaborador', 'VL'),
  ('import-700', 700, 'Fernandez Diez Sofia', NULL, '', 'TIMBRES 840 4 B CASTELAR', 'Activo', 'Socio colaborador', 'FD'),
  ('import-701', 701, 'Gallo Liliana', NULL, '', 'SAN MARTIN 1009 URDAMPILLETA', 'Activo', 'Socio colaborador', 'GL'),
  ('import-702', 702, 'Diez Cristina', NULL, '', 'J.B.ALBERTI 147 URDAMPILLETA', 'Activo', 'Socio colaborador', 'DC'),
  ('import-704', 704, 'Diaz Sandra', NULL, '', 'BELGRANO 237 URDAMPILLETA', 'Activo', 'Socio colaborador', 'DS'),
  ('import-705', 705, 'Vicente Miriam', NULL, '', 'PELLEGRINI 1019 URDAMPILLETA', 'Activo', 'Socio colaborador', 'VM'),
  ('import-706', 706, 'Calderero Micaela', NULL, '', 'RIVADAVIA 765 URDAMPÍLLETA', 'Activo', 'Socio colaborador', 'CM'),
  ('import-707', 707, 'Polaco Valeria', NULL, '', 'URDAMPILLETA', 'Activo', 'Socio colaborador', 'PV'),
  ('import-708', 708, 'Lencina Gisella', NULL, '', 'LAVALLE 253 URDAMPILLETA', 'Activo', 'Socio colaborador', 'LG'),
  ('import-709', 709, 'Sierra Flavia', NULL, '', 'I. RIVAS 500 BOLIVAR', 'Activo', 'Socio colaborador', 'SF'),
  ('import-710', 710, 'Gonzalez Mabel', NULL, '', 'GUEMES 326 BOLIVAR', 'Activo', 'Socio colaborador', 'GM'),
  ('import-711', 711, 'Fernandez Giuliana', NULL, '', 'BARRIO COOP CASA 85 BOLIVAR', 'Activo', 'Socio colaborador', 'FG'),
  ('import-712', 712, 'Ricabarra Mariana', NULL, '', '624787', 'Activo', 'Socio colaborador', 'RM'),
  ('import-713', 713, 'Crespi Silvia Rosa', NULL, '', 'laprida 130', 'Activo', 'Socio colaborador', 'CS'),
  ('import-714', 714, 'Ziarzolo Florencia Selene', NULL, '', 'GUEMES 735', 'Activo', 'Socio colaborador', 'ZF'),
  ('import-715', 715, 'Costilla Marina Soledad', NULL, '', 'ESPAÑA 522 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CM'),
  ('import-718', 718, 'Marzano Analia Elizabeth', NULL, '223156840830', '', 'Activo', 'Socio colaborador', 'MA'),
  ('import-719', 719, 'Guzman Patricia Roxana', NULL, '', 'ALBERTI 559 BOLIVAR', 'Activo', 'Socio colaborador', 'GP'),
  ('import-721', 721, 'Batistelli Analia', NULL, '', '545794', 'Activo', 'Socio colaborador', 'BA'),
  ('import-723', 723, 'Urrutia Maria Julia', NULL, '', 'QUINTANA 575', 'Activo', 'Socio colaborador', 'UM'),
  ('import-724', 724, 'Panaro Alicia Lilian', NULL, '', 'CUARTEL 2', 'Activo', 'Socio colaborador', 'PA'),
  ('import-725', 725, 'Iglesias Nancy', NULL, '', 'LAS HERAS 412', 'Activo', 'Socio colaborador', 'IN'),
  ('import-726', 726, 'Ibañez Karen', NULL, '', 'SAN MARTIN 246 BOLIVAR', 'Activo', 'Socio colaborador', 'IK')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-727', 727, 'Pagola Guillermo Fabian', NULL, '', 'PELLEGRINI 336', 'Activo', 'Socio colaborador', 'PG'),
  ('import-729', 729, 'Carona Eliana Marisol', NULL, '', 'o 907 DAIREAUX', 'Activo', 'Socio colaborador', 'CE'),
  ('import-730', 730, 'Fallecen Mirta', NULL, '', 'S QUINTAS PIROVANO', 'Activo', 'Socio colaborador', 'FM'),
  ('import-731', 731, 'Fallecen Gisella', NULL, '', 'AVDA REPETO PIROVANO', 'Activo', 'Socio colaborador', 'FG'),
  ('import-732', 732, 'Bellomo Elida', NULL, '', 'LAPRIDA 278', 'Activo', 'Socio colaborador', 'BE'),
  ('import-733', 733, 'Morales Mauricio Javier', NULL, '', 'Belgrano 102 Gamacenter', 'Activo', 'Socio colaborador', 'MM'),
  ('import-734', 734, 'Valdez Maria Cristina', NULL, '', 'Laprida 265', 'Activo', 'Socio colaborador', 'VM'),
  ('import-736', 736, 'Parrondo Sandra', NULL, '', 'San Martin 450', 'Activo', 'Socio colaborador', 'PS'),
  ('import-737', 737, 'Casella Romina Vanesa', NULL, '', '3 de febrero 751', 'Activo', 'Socio colaborador', 'CR'),
  ('import-738', 738, 'Bracamonte Graciela Beatriz', NULL, '', 'Ameghino 435', 'Activo', 'Socio colaborador', 'BG'),
  ('import-739', 739, 'Siervo Lorena', NULL, '', 'San Martin 1201', 'Activo', 'Socio colaborador', 'SL'),
  ('import-740', 740, 'Meson Daniela Beatriz', NULL, '', 'Gral Paz 1301', 'Activo', 'Socio colaborador', 'MD'),
  ('import-741', 741, 'Fernandez Maria G.', NULL, '', '448752', 'Activo', 'Socio colaborador', 'FM'),
  ('import-742', 742, 'Buglione Victoria', NULL, '', '475240', 'Activo', 'Socio colaborador', 'BV'),
  ('import-743', 743, 'Picazo Silvia', NULL, '', '441077', 'Activo', 'Socio colaborador', 'PS'),
  ('import-744', 744, 'Vicente Maria Belen', NULL, '', '619210', 'Activo', 'Socio colaborador', 'VM'),
  ('import-746', 746, 'Rodriguez Maria De Los Angeles', NULL, '', '532428', 'Activo', 'Socio colaborador', 'RM'),
  ('import-749', 749, 'Caldara Rosana Monica', NULL, '', '468527', 'Activo', 'Socio colaborador', 'CR'),
  ('import-750', 750, 'Zandepiacomi Maria Emilia', NULL, '', '479333', 'Activo', 'Socio colaborador', 'ZM'),
  ('import-751', 751, 'Rodriguez Marina Susana', NULL, '', '468813', 'Activo', 'Socio colaborador', 'RM'),
  ('import-752', 752, 'Garrote Patricia Marcela', NULL, '', '531007', 'Activo', 'Socio colaborador', 'GP'),
  ('import-753', 753, 'Bentin Miryam Elisabet', NULL, '', '478075', 'Activo', 'Socio colaborador', 'BM'),
  ('import-754', 754, 'Morena Estela Lucrecia', NULL, '', '411446', 'Activo', 'Socio colaborador', 'ME'),
  ('import-755', 755, 'Astengo Cintia Soledad', NULL, '', '536987', 'Activo', 'Socio colaborador', 'AC'),
  ('import-756', 756, 'Mendoza Jorgelina', NULL, '', '471860', 'Activo', 'Socio colaborador', 'MJ'),
  ('import-757', 757, 'Ojeda Raul Alberto', NULL, '', 'Moreno 170 Urdampilleta', 'Activo', 'Socio colaborador', 'OR'),
  ('import-758', 758, 'Milani Fabiana', NULL, '', 'Irigoyen 157', 'Activo', 'Socio colaborador', 'MF'),
  ('import-760', 760, 'Garcia Maria Lujan', NULL, '', '517784', 'Activo', 'Socio colaborador', 'GM'),
  ('import-762', 762, 'Roque Maria Claudia', NULL, '', '514877', 'Activo', 'Socio colaborador', 'RM'),
  ('import-763', 763, 'Churrout Mirta Nliliana', NULL, '', '610130', 'Activo', 'Socio colaborador', 'CM'),
  ('import-765', 765, 'Garcia Emilse', NULL, '', '473056', 'Activo', 'Socio colaborador', 'GE'),
  ('import-766', 766, 'Pacho Nelida Beatriz', NULL, '', '490196', 'Activo', 'Socio colaborador', 'PN'),
  ('import-767', 767, 'Misky Patricia', NULL, '1162761822', '', 'Activo', 'Socio colaborador', 'MP'),
  ('import-768', 768, 'Cusco Alicia', NULL, '', '471715', 'Activo', 'Socio colaborador', 'CA'),
  ('import-770', 770, 'Fallecen Maria Lujan', NULL, '', '408848', 'Activo', 'Socio colaborador', 'FM'),
  ('import-771', 771, 'Gonzalez Rocio Belen', NULL, '', '517754', 'Activo', 'Socio colaborador', 'GR'),
  ('import-773', 773, 'Portilla Adriana Noemi', NULL, '', '537392', 'Activo', 'Socio colaborador', 'PA'),
  ('import-774', 774, 'Gonzalez Gissela N', NULL, '', '406360', 'Activo', 'Socio colaborador', 'GG'),
  ('import-775', 775, 'Tejero Monica', NULL, '', '407440', 'Activo', 'Socio colaborador', 'TM'),
  ('import-776', 776, 'Iriarte Lucas H', NULL, '', '473676', 'Activo', 'Socio colaborador', 'IL'),
  ('import-778', 778, 'Manghi Sofia', NULL, '', 'MORENO 1157 OLAVARRIA', 'Activo', 'Socio colaborador', 'MS'),
  ('import-779', 779, 'Branca J Manuel', NULL, '', '404894', 'Activo', 'Socio colaborador', 'BJ'),
  ('import-780', 780, 'Pacho Cesar', NULL, '', 'guemes 629 bolivar', 'Activo', 'Socio colaborador', 'PC'),
  ('import-781', 781, 'Marcolini Monica Noemi', NULL, '', 'guemes 629', 'Activo', 'Socio colaborador', 'MM'),
  ('import-782', 782, 'Cernadas Silvia Margarita', NULL, '', 'laprida 57 urdampilleta', 'Activo', 'Socio colaborador', 'CS'),
  ('import-783', 783, 'Oliva Dina Fabiola', NULL, '', '613222', 'Activo', 'Socio colaborador', 'OD'),
  ('import-784', 784, 'Luque Andrea Yanina', NULL, '', 'NICOLAS SARLO 1314 CASA 90 ZOR', 'Activo', 'Socio colaborador', 'LA'),
  ('import-785', 785, 'Zeni Daniel Juan', NULL, '', '144 N 2356 BERAZATEGUI', 'Activo', 'Socio colaborador', 'ZD'),
  ('import-786', 786, 'Prieto Maria Alejandra', NULL, '', '144 2356 BERAZATEGUI', 'Activo', 'Socio colaborador', 'PM'),
  ('import-787', 787, 'Rodriguez Ana Maria', NULL, '', 'DIAGONAL ROTETA S/N PIROVANO', 'Activo', 'Socio colaborador', 'RA'),
  ('import-789', 789, 'Artola Agustina', NULL, '', 'MORENO47', 'Activo', 'Socio colaborador', 'AA'),
  ('import-790', 790, 'Moulia Lucrecia', NULL, '', 'GRAL. P AZ 561 BOLIVAR', 'Activo', 'Socio colaborador', 'ML'),
  ('import-791', 791, 'Cisneros Alicia Esther', NULL, '', 'FORMOSA 41 BOLIVAR', 'Activo', 'Socio colaborador', 'CA'),
  ('import-792', 792, 'Oriozabala Carlos Alberto', NULL, '', 'FORMOSA 41 BOLIVAR', 'Activo', 'Socio colaborador', 'OC'),
  ('import-793', 793, 'Reguero Diana Gabriela', NULL, '', 'P GARCIA 545 B SOLIDARIDAD', 'Activo', 'Socio colaborador', 'RD'),
  ('import-794', 794, 'Gimenez Adriana Elizabeth', NULL, '', 'J. M. FANGIO 826 BOLIVAR', 'Activo', 'Socio colaborador', 'GA'),
  ('import-795', 795, 'Arcella Varela Alejandra Dora', NULL, '', 'S. PLAZA 645 BOLIVAR', 'Activo', 'Socio colaborador', 'AV'),
  ('import-796', 796, 'Cardacce Matias', NULL, '', 'BROWN 465 BOLIVAR', 'Activo', 'Socio colaborador', 'CM'),
  ('import-799', 799, 'Baldi Marisa Silvia Lujan', NULL, '', 'CATRIEL 85 B.S JUAN BOLIVAR', 'Activo', 'Socio colaborador', 'BM'),
  ('import-800', 800, 'Bais Nelly', NULL, '', 'ARENALES 669 BOLIVAR', 'Activo', 'Socio colaborador', 'BN'),
  ('import-801', 801, 'Cepeda Maria Ines', NULL, '', 'ALBERTI 1068 BOLIVAR', 'Activo', 'Socio colaborador', 'CM'),
  ('import-802', 802, 'Ojuez De Cepeda Ana Ines', NULL, '', 'J.NEWBERY 435 BOLIVAR', 'Activo', 'Socio colaborador', 'OD'),
  ('import-803', 803, 'Cepeda Ana Lia', NULL, '', '25 DE MAYO 1268', 'Activo', 'Socio colaborador', 'CA'),
  ('import-805', 805, 'Bonavigna Adriana Mabel', NULL, '', 'REBUCION 363 BOLIVAR', 'Activo', 'Socio colaborador', 'BA'),
  ('import-806', 806, 'Fibiger Natalia Yanina Andrea', NULL, '', 'CASTELLI 925 BOLIVAR', 'Activo', 'Socio colaborador', 'FN'),
  ('import-807', 807, 'Rodriguez Maria Emilia', NULL, '', 'ROCA 252 BOLIVAR', 'Activo', 'Socio colaborador', 'RM'),
  ('import-808', 808, 'Iglesias Romina Victoria', NULL, '', '4 1348 LA PLATA', 'Activo', 'Socio colaborador', 'IR'),
  ('import-810', 810, 'Mouret Marta Virginia', NULL, '', 'C.DEL MONTE 642 CALFUCURA', 'Activo', 'Socio colaborador', 'MM'),
  ('import-812', 812, 'Mendez Ciro', NULL, '', 'BLAS PARERA 1133 MARDEL', 'Activo', 'Socio colaborador', 'MC'),
  ('import-813', 813, 'Mendez Mora', NULL, '', 'BLAS PARERA 1133 MARDEL', 'Activo', 'Socio colaborador', 'MM'),
  ('import-814', 814, 'Quintana Vilma', NULL, '', 'AV MARIANO UNZUE 1481', 'Activo', 'Socio colaborador', 'QV'),
  ('import-815', 815, 'Garavano Juan Pedro', NULL, '', '7 entre 47 y 48 LA PLATA', 'Activo', 'Socio colaborador', 'GJ'),
  ('import-816', 816, 'Carroze Gladys', NULL, '', 'TUCUMAN 1706 BRAGADO', 'Activo', 'Socio colaborador', 'CG'),
  ('import-817', 817, 'Haag Evangelin Haydee', NULL, '', 'S. PLAZA 147 BOLIVAR', 'Activo', 'Socio colaborador', 'HE'),
  ('import-818', 818, 'Falle Maria Soledad', NULL, '', 'AMECHINO 635 URDAMPILLETA', 'Activo', 'Socio colaborador', 'FM'),
  ('import-819', 819, 'Chiminella Micaela', NULL, '', 'LAVALLE 280 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CM'),
  ('import-820', 820, 'Coronel Veronica Esther', NULL, '', 'MAIPU 84 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CV'),
  ('import-821', 821, 'Della Rosa Maria Luz', NULL, '', 'IRIGOYE 502 URDAMPILLETA', 'Activo', 'Socio colaborador', 'DR'),
  ('import-822', 822, 'Lede Mendoza Ariel', NULL, '', '20 BIS6320 LA PLATA', 'Activo', 'Socio colaborador', 'LM'),
  ('import-823', 823, 'Lede Mendoza Fernando', NULL, '', '66 m 519 LA PLATA', 'Activo', 'Socio colaborador', 'LM'),
  ('import-824', 824, 'Saffores Maria Angelica', NULL, '', 'SAN MARTIN 1001 URDAMPILLETA', 'Activo', 'Socio colaborador', 'SM'),
  ('import-825', 825, 'Godofredo Karina', NULL, '', 'SAN MARTIN 1148 URDAMPILLETA', 'Activo', 'Socio colaborador', 'GK'),
  ('import-826', 826, 'Gonzalez Ricardo', NULL, '', 'RIVADAVIA 674 BOLIVAR', 'Activo', 'Socio colaborador', 'GR'),
  ('import-827', 827, 'Sanchez Marcela Ines', NULL, '', 'MARTIN 665 URDAMPILLETA', 'Activo', 'Socio colaborador', 'SM'),
  ('import-828', 828, 'Pedruelo Leonardo', NULL, '', 'SAAVEDRA469 URDAMPILLETA', 'Activo', 'Socio colaborador', 'PL'),
  ('import-829', 829, 'Allende Maria Lucrecia', NULL, '', 'A. ARGENTINA 480 URDAMPILLETA', 'Activo', 'Socio colaborador', 'AM'),
  ('import-831', 831, 'Martin Maria Fernanda', NULL, '', 'BROWNN 320 OP BROWN BOLIVAR', 'Activo', 'Socio colaborador', 'MM'),
  ('import-832', 832, 'Medina Sandra Elena', NULL, '', 'SARMIENTO 330 URDAMPILLETA', 'Activo', 'Socio colaborador', 'MS'),
  ('import-833', 833, 'Perez Mara', NULL, '', 'San Juan 25', 'Activo', 'Socio colaborador', 'PM'),
  ('import-834', 834, 'Miramon Diego Javier', NULL, '', 'SAAVEDRA 77 BOLIVAR', 'Activo', 'Socio colaborador', 'MD'),
  ('import-835', 835, 'Bercovich Rosita', NULL, '', 'PRINGLES 77 BOLIVAR', 'Activo', 'Socio colaborador', 'BR'),
  ('import-836', 836, 'Iriarte Maria Angela', NULL, '', 'RIVADAVIA 1082 GRAL RODRIGUEZ', 'Activo', 'Socio colaborador', 'IM'),
  ('import-837', 837, 'Real Magdalena', NULL, '', 'AVELLANEDA 661 BOLIVAR', 'Activo', 'Socio colaborador', 'RM'),
  ('import-838', 838, 'Godoy Maria Emilia', NULL, '', 'MATHEU 379 BOLIVAR', 'Activo', 'Socio colaborador', 'GM'),
  ('import-839', 839, 'Schwab Hernan', NULL, '', 'RIVADAVIA NORTE 634 AZUL', 'Activo', 'Socio colaborador', 'SH'),
  ('import-840', 840, 'Martinez Viviana Elisabet', NULL, '', 'VILLALONGA . CARMEN DE PATAGON', 'Activo', 'Socio colaborador', 'MV'),
  ('import-842', 842, 'Bailiarini Marialuzu', NULL, '', '616545', 'Activo', 'Socio colaborador', 'BM'),
  ('import-843', 843, 'Dadante Gustavo Alberto', NULL, '', '612947', 'Activo', 'Socio colaborador', 'DG'),
  ('import-844', 844, 'Hernandez Analia Graciela', NULL, '', '611421', 'Activo', 'Socio colaborador', 'HA'),
  ('import-845', 845, 'Bruno Analia Lujan', NULL, '', '625599', 'Activo', 'Socio colaborador', 'BA')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;

INSERT INTO members (id, external_id, name, email, phone, address, status, plan, avatar)
VALUES
  ('import-846', 846, 'Hernandez Jorge Omar', NULL, '', '409291', 'Activo', 'Socio colaborador', 'HJ'),
  ('import-847', 847, 'Dia Z Piñeiro Patricia Esther', NULL, '', '404010', 'Activo', 'Socio colaborador', 'DZ'),
  ('import-848', 848, 'Peluso Claudia', NULL, '', '624118', 'Activo', 'Socio colaborador', 'PC'),
  ('import-849', 849, 'Macchiaroli Jose Luis', NULL, '', '615109', 'Activo', 'Socio colaborador', 'MJ'),
  ('import-850', 850, 'Lopardo Marisa C Ristina', NULL, '', '407439', 'Activo', 'Socio colaborador', 'LM'),
  ('import-851', 851, 'Beherens Luis German', NULL, '', '619431', 'Activo', 'Socio colaborador', 'BL'),
  ('import-852', 852, 'Poffo Roberto Mario', NULL, '', '620679', 'Activo', 'Socio colaborador', 'PR'),
  ('import-853', 853, 'Fabris Pablo', NULL, '', 'VIAMONTE 735 BOLIVAR', 'Activo', 'Socio colaborador', 'FP'),
  ('import-854', 854, 'Tamborenea Maria Jose', NULL, '1152480386', '', 'Activo', 'Socio colaborador', 'TM'),
  ('import-855', 855, 'Iriarte Milagros Del Rocio', NULL, '', 'R. PEÑA 640', 'Activo', 'Socio colaborador', 'IM'),
  ('import-856', 856, 'Previtali Maximiliano', NULL, '', 'SANTIAGO DEL ESTERO', 'Activo', 'Socio colaborador', 'PM'),
  ('import-857', 857, 'Laopez Maria Laura', NULL, '', 'AMADO 725 BOLIVAR', 'Activo', 'Socio colaborador', 'LM'),
  ('import-858', 858, 'Rodriguez Maria Alicia', NULL, '', 'SAN MARTIN 355 BOLIVAR', 'Activo', 'Socio colaborador', 'RM'),
  ('import-859', 859, 'Barrera Valeria Elizabet', NULL, '', '484854', 'Activo', 'Socio colaborador', 'BV'),
  ('import-860', 860, 'Torrontegui Ayelen', NULL, '', '464120', 'Activo', 'Socio colaborador', 'TA'),
  ('import-861', 861, 'Iglesia Estela', NULL, '', '497040', 'Activo', 'Socio colaborador', 'IE'),
  ('import-862', 862, 'Azparren Andrea Marisol.', NULL, '', '413542', 'Activo', 'Socio colaborador', 'AA'),
  ('import-863', 863, 'Palacios Maria Belen', NULL, '', '404544', 'Activo', 'Socio colaborador', 'PM'),
  ('import-864', 864, 'Calvo Maria Del Carmen', NULL, '', '533880', 'Activo', 'Socio colaborador', 'CM'),
  ('import-865', 865, 'Palomino Maria Lujan', NULL, '', '402647', 'Activo', 'Socio colaborador', 'PM'),
  ('import-866', 866, 'Pacheco Magali', NULL, '', '531857', 'Activo', 'Socio colaborador', 'PM'),
  ('import-867', 867, 'Prieto Maria Elena', NULL, '', '531297', 'Activo', 'Socio colaborador', 'PM'),
  ('import-868', 868, 'Monaco Maria Alejandra', NULL, '', '518434', 'Activo', 'Socio colaborador', 'MM'),
  ('import-869', 869, 'Saffores Estefania Denise', NULL, '', '409746', 'Activo', 'Socio colaborador', 'SE'),
  ('import-870', 870, 'Criado Beatriz', NULL, '', '480373', 'Activo', 'Socio colaborador', 'CB'),
  ('import-871', 871, 'Irarzun Maria Josefina', NULL, '', 'PALAVECINO 580', 'Activo', 'Socio colaborador', 'IM'),
  ('import-872', 872, 'Arredondo Mariangeles', NULL, '', '619614', 'Activo', 'Socio colaborador', 'AM'),
  ('import-873', 873, 'Fredes Bernardo Gabriel', NULL, '2314410683', '', 'Activo', 'Socio colaborador', 'FB'),
  ('import-874', 874, 'Luengo Analia', NULL, '2314626178', '', 'Activo', 'Socio colaborador', 'LA'),
  ('import-875', 875, 'Olivera M. Luz', NULL, '', 'Saavedra 256 Urdampilleta', 'Activo', 'Socio colaborador', 'OM'),
  ('import-876', 876, 'Muggeri Aldana Noelia', NULL, '2314446131', '', 'Activo', 'Socio colaborador', 'MA'),
  ('import-877', 877, 'Zucalli Marcelo', NULL, '2215010191', '', 'Activo', 'Socio colaborador', 'ZM'),
  ('import-878', 878, 'Jauregui Monica', NULL, '2314623765', '', 'Activo', 'Socio colaborador', 'JM'),
  ('import-879', 879, 'Cepeda Maria Eugenia', NULL, '', '20 nro35 entre 7 y 9 BALCARCE', 'Activo', 'Socio colaborador', 'CM'),
  ('import-880', 880, 'Pisano Marcelaf Fabiana', NULL, '', 'ALVARADO 125 BOLIVAR', 'Activo', 'Socio colaborador', 'PM'),
  ('import-881', 881, 'Diz Lorena Andrea', NULL, '', 'COSQUIN 1839 DTO 15 LA MATANZA', 'Activo', 'Socio colaborador', 'DL'),
  ('import-882', 882, 'Fernandez Hugo Alberto', NULL, '', 'IRIGOYEN 946 URDAMPILLETA', 'Activo', 'Socio colaborador', 'FH'),
  ('import-883', 883, 'Carona Carlos Javier', NULL, '', 'LAVALLE 160 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CC'),
  ('import-884', 884, 'Alzueta Edgardo Alfredo', NULL, '', 'SARMIENTO 337 URDAMPILLETA', 'Activo', 'Socio colaborador', 'AE'),
  ('import-885', 885, 'Batistuta Carlos', NULL, '', 'SARMIENTO 1148 URDAMPILLETA', 'Activo', 'Socio colaborador', 'BC'),
  ('import-886', 886, 'Cisneros Maria Betina', NULL, '1160274574', '', 'Activo', 'Socio colaborador', 'CM'),
  ('import-887', 887, 'Sarraigoicoechea Mia', NULL, '2314579080', '', 'Activo', 'Socio colaborador', 'SM'),
  ('import-888', 888, 'Abat Mariana Jacinta', NULL, '', 'COLON 30 URDAMPILLETA', 'Activo', 'Socio colaborador', 'AM'),
  ('import-889', 889, 'Zurdo Marta Alicia', NULL, '', 'SAN MARTIN 685 URDAMPILLETA', 'Activo', 'Socio colaborador', 'ZM'),
  ('import-890', 890, 'Lorena Analia', NULL, '', 'PASTEUR 977 URDAMPILLETA', 'Activo', 'Socio colaborador', 'LA'),
  ('import-891', 891, 'Saffores Maria Jimena', NULL, '', 'CHACABUCO 190 URDAMPILLETA', 'Activo', 'Socio colaborador', 'SM'),
  ('import-892', 892, 'Crepso Julia', NULL, '', 'ARENALES 119 URDAMPILLETA', 'Activo', 'Socio colaborador', 'CJ'),
  ('import-893', 893, 'Pisano Haydee', NULL, '', 'viamonte 20 BOLIVAR', 'Activo', 'Socio colaborador', 'PH'),
  ('import-894', 894, 'Gonzalez Marta Susana', NULL, '', 'AV ITALIA 927 URDAMPILLETA', 'Activo', 'Socio colaborador', 'GM')
ON CONFLICT (id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  name = EXCLUDED.name,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  plan = EXCLUDED.plan,
  avatar = EXCLUDED.avatar;
