"use client";
import { useEffect, useMemo, useState } from "react";
import type React from "react";
import { Shell } from "@/components/shell";
import { Icon } from "@/components/icons";
import { demoMembers, type Member } from "@/lib/data";

type MemberForm = { name: string; email: string; phone: string; plan: string; status: Member["status"] };
const blank: MemberForm = { name:"", email:"", phone:"", plan:"Socio colaborador", status:"Activo" };

export default function MembersPage() {
  const [members, setMembers] = useState<Member[]>(demoMembers);
  useEffect(() => { fetch("/api/members").then((response) => response.json()).then((data) => { if (Array.isArray(data.members)) setMembers(data.members); }).catch(() => undefined); }, []);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("Todos");
  const [form, setForm] = useState<MemberForm>(blank);
  const [editing, setEditing] = useState<Member | null>(null);
  const [open, setOpen] = useState(false);
  const filtered = useMemo(() => members.filter(m => (m.name + (m.email ?? "") + (m.address ?? "")).toLowerCase().includes(query.toLowerCase()) && (status === "Todos" || m.status === status)), [members, query, status]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const payload = {...form, avatar: form.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}; const url = editing ? `/api/members/${editing.id}` : "/api/members"; const response = await fetch(url, { method: editing ? "PUT" : "POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) }); const data = await response.json(); const next = data.member as Member; setMembers(current => editing ? current.map(m => m.id === editing.id ? {...m, ...next} : m) : [next, ...current]); setOpen(false); setEditing(null); setForm(blank); };
  const remove = async (member: Member) => { if (!window.confirm(`¿Dar de baja a ${member.name}?`)) return; await fetch(`/api/members/${member.id}`, {method:"DELETE"}); setMembers(current => current.filter(m => m.id !== member.id)); };
  const startEdit = (member: Member) => { setEditing(member); setForm({name:member.name,email:member.email ?? "",phone:member.phone,plan:member.plan,status:member.status}); setOpen(true); };
  return <Shell current="Socios"><div className="content"><div className="eyebrow">Administración</div><h1 className="title">Socios</h1><p className="intro">Gestioná altas, datos de contacto, planes y estado de cada integrante.</p><div className="toolbar"><div style={{display:"flex",gap:10,flex:1}}><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre, email o domicilio"/><select className="secondary" value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Activo</option><option>Pendiente</option><option>Inactivo</option></select></div><button className="primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Icon name="plus"/> <span style={{marginLeft:7}}>Nuevo socio</span></button></div><div className="card section-card"><div className="table-wrap"><table className="table"><thead><tr><th>Socio</th><th>Contacto</th><th>Alta</th><th>Plan</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td><div className="person"><div className="avatar">{m.avatar}</div><div><div className="person-name">{m.name}</div><div className="person-mail">{m.email || "Email pendiente de completar"}</div></div></div></td><td>{m.phone || m.address || "Sin dato"}</td><td>{m.joinedAt}</td><td>{m.plan}</td><td><span className={`status ${m.status === "Activo"?"status-active":m.status === "Pendiente"?"status-pending":"status-inactive"}`}>{m.status}</span></td><td><button className="table-action" onClick={()=>startEdit(m)}>Editar</button><button className="table-action danger" onClick={()=>remove(m)}>Baja</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No hay socios que coincidan con la búsqueda.</div>}</div></div>{open&&<div className="modal-backdrop"><form className="modal card" onSubmit={save}><div className="card-head"><div className="card-title">{editing?"Editar socio":"Nuevo socio"}</div><button type="button" className="close" onClick={()=>setOpen(false)}>×</button></div><label>Nombre completo<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Plan<select value={form.plan} onChange={e=>setForm({...form,plan:e.target.value})}><option>Socio colaborador</option><option>Socio fundador</option><option>Socio benefactor</option></select></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Member["status"]})}><option>Activo</option><option>Pendiente</option><option>Inactivo</option></select></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Guardar socio</button></div></form></div>}</div></Shell>;
}
