"use client";

import { useState } from "react";
import { signIn } from "next-auth/react";
import Link from "next/link";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [alias, setAlias] = useState(""); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); const result = await signIn("credentials", { email, alias, callbackUrl: "/dashboard", redirect: false }); if (result?.error) setError("El email o alias no son válidos."); else window.location.href = "/dashboard"; };
  return <main className="login-page"><section className="login-aside"><div className="login-brand"><img src="/site-assets/logo-blanco-sobre-azul.png" alt="Uniendo Sonrisas Asociación Civil"/><div><strong>Uniendo Sonrisas</strong><span>Administración de la<br/>Asociación Civil</span></div></div><div><div className="eyebrow" style={{ color: "#f6c65e" }}>Panel de gestión</div><h1>El compromiso se construye juntos.</h1><p>Administrá socios, aportes mensuales y el impacto de la asociación civil desde un solo lugar.</p></div></section><section className="login-card"><div className="login-box"><Link href="/" className="back">← Volver al inicio</Link><div className="eyebrow">Administración de la asociación civil</div><h2>Ingresá al gestor</h2><p>Usá tu email y el alias de tres palabras que te compartió la fundación.</p><form className="credentials-form" onSubmit={submit}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="tu@email.com"/></label><label>Alias de acceso<input required value={alias} onChange={(event) => setAlias(event.target.value)} placeholder="sol-risa-luz"/></label>{error && <div className="login-error">{error}</div>}<button className="primary login-submit">Ingresar</button></form><div className="login-divider"><span>o</span></div><button className="google-btn" onClick={() => signIn("google", { callbackUrl: "/dashboard" })}><span style={{ fontSize: 18, verticalAlign: "-2px", marginRight: 9 }}>G</span> Continuar con Google</button><p className="demo-note">Demo local: <code>admin@uniendosonrisas.org</code> · <code>sol-risa-luz</code></p></div></section></main>;
}
